# Generated by Django 5.0.6 on 2024-05-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_name'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empledo',
            new_name='Empleado',
        ),
    ]
